spring:
  application:
    name: tomcat

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/tomcatnetty
    username: root
    password: PCs14025487
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
