spring:
  application:
    name: netty
  r2dbc:
#    url: r2dbc:mysql://localhost:3306/tomcatnetty
    url: r2dbc:mysql://host.docker.internal:3306/tomcatnetty
    username: root
    password: PCs14025487
server:
  port: 8081
